<h2><?= $header ?></h2>

<?php foreach ($messages as $message) : ?>
    <p class="error"><?= $message ?></p>
<?php endforeach ?>

<form action="" method="post">
    <label for="name">Name*:</label><br />
    <input type="text" id="name" name="name" value="<?= $name; ?>" /><br />

    <label for="description">Description*:</label><br />
    <textarea id="description" name="description" cols="30" rows="10" value=""><?= $description; ?></textarea><br />

    <label for="status">Status*:</label><br />
    <select id="status" name="status">
        <option value=""></option>
        <option value="In Stock" <?php if ($status == 'In Stock') {echo 'selected';} ?>>In stock</option>
        <option value="Out of Stock" <?php if ($status == 'Out of Stock') {echo 'selected';} ?>>Out of stock</option>
        <option value="Low" <?php if ($status == 'Low') {echo 'selected';} ?>>Low</option>
    </select><br /> 

    <label for="category">Category:</label><br />
    <select id="category" name="category">
        <option value=""></option>
        
        <?php foreach ($categories as $cat) : ?>
            <option value="<?= $cat['name']; ?>" <?php if ($cat['name'] == $category) {echo 'selected';} ?>><?= $cat['name']; ?></option>
        <?php endforeach; ?>
    </select>

    <p>* - this fields are necessery</p>
    
    <p><input type="submit" name="addeditbutton" value="<?= $button ?>" /></p>
</form>