<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="/aurora/" />
        <link rel="stylesheet" href="style1.css" type="text/css"/>
        <meta charset="UTF-8" />
        <title><?= $title ?></title>
    </head>

    <body>
        <header>
            <h1>Simple articles management page</h1>
        </header>

        <?php foreach ($messages as $message) : ?>
            <p class="message"><?= $message ?></p>
        <?php endforeach ?>
        
        <nav>
            <ul>
                <li><a href="/aurora">Home</a></li>
                <li><a href="add">Add a new item</a></li>
                <li><a href="register">Register a new user</a></li>
            </ul>
            <?php if(!$user) : ?>
                <div>
                    <form action="" method="post">
                        <label for="login">Have an account? Login:</label>
                        <input class="loginField" type="text" name="login" value="" reqiured />
                        <label for="password">Password:</label>
                        <input class="loginField" type="password" name="password" value="" reqiured />
                        <button class="goButton" type="submit" name="authentification">Go!</button>
                    </form>
                </div>
            <?php else: ?>
                <div>
                    <form action="" method="post">
                        <span>You are logged in as <?= $user; ?></span>
                        <button class="goButton" type="submit" name="logout">Logout</button>
                    </form>
                </div>
            <?php endif; ?>
        </nav>
       
        <br />

        <?php $this->controller->renderView();?>
        
    </body>
</html>